### ISSUE TITLE
Switching overlays turn on some disabled overlay items

### ISSUE THREAD

**Issue by sanyer** [CXWorld/CapFrameX#224]
I have two overlays:
- first with plenty of info but without Capture service status (but with Capture timer) and Run history
- second with some info and with only Capture timer

Switching between overlay configs enables Run history (and sometimes also Capture service status) on the first one, which is unexpected and undesirable behavior.

**Comment by DevTechProfile** [comment]
Switching configs enables certain flags. @Taxxor90 Wäre das was für dich?

**Comment by Taxxor90** [comment]
I couldn't reproduce the capture service status entry being activated on config switch when it wasn't activated in said config but I fixed the run history behaviour.

I've also removed the disabling of the checkbox when the history is not active so that you can now set up all the overlay configs with the history deactivated and when you enable it, you'll only see it in those configs you've selected the entry.
1453d0faafb155f2b1cded45e32478d8096c2769

**Comment by sanyer** [comment]
Hey @Taxxor90 , I definitely press Save button.
I'll try again.

**Comment by sanyer** [comment]
Yeah, still happens. Config 2 has it disabled at first, but after switching to config 3, which has Run History, it also gets enabled on config 2.
![Animation_kgy](https://user-images.githubusercontent.com/1888892/204129211-5f3e08ed-c715-4e6a-ad96-ab1db49e00f8.gif)

**Comment by Taxxor90** [comment]
You have to use the latest version from https://archive.capframex.com/

**Comment by sanyer** [comment]
oh right, now I understand. Thinking slow today 😬 
Thanks, @Taxxor90 ! It is indeed fixed. Don't see the Capture Service status problem also, perhaps that was a one off, will let you know if it appears again.

**Comment by Taxxor90** [comment]
Alright, closing this for now. Feel free to reopen it when you found a way to reproduce the issue with the capture service
