### ISSUE TITLE
Higher than normal CPU usage on desktop/idle on Intel 12th Gen + RDNA3 platform

### ISSUE THREAD

**Issue by RodroG-85** [CXWorld/CapFrameX#255]
Hello. I noticed again that the CapFrameX process shows higher than expected CPU utilization (constant CPU usage fluctuations, about 1% to 2%) on desktop/idle conditions with Overlay enabled using v1.7.1 and the latest pre-release beta build.

While in-game and capturing, the CX CPU % sensor shows continuous fluctuations from 0.0% to 0.3% max. This one seems a more expected percentage, though.

I had to roll back to version 1.6.8 to see a steady 0% CPU usage of CapFrameX.exe on desktop/idle/minimized-to-system-tray conditions with overlay features enabled. However, this version lacks many recent and new features, including Win 11 (coming from PresentMon v1.8.0 and later versions) and RDN3 support.

My system/platform specs are attached below:
[DxDiag.txt](https://github.com/CXWorld/CapFrameX/files/12640114/DxDiag.txt)

Please, could you look into this?

Best regards.

**Comment by DevTechProfile** [comment]
I can confirm the behavior, see here: https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/issues/11

**Comment by RodroG-85** [comment]
Thank you very much, as always, mate. Sorry for the delay. I was playing
Starfield non-stop. 😄

Would it be possible to mitigate or fix this behavior?

**Comment by DevTechProfile** [comment]
You can try to use the "ADL Fallback". At the end, it's up to AMD to fix this. 

![image](https://github.com/CXWorld/CapFrameX/assets/30285858/b8edf509-ea10-4b56-a540-00a66b8c8fe7)

**Comment by RodroG-85** [comment]
Thank you. I will try it. Hopefully, AMD will take the report into account at some point.

**Comment by RodroG-85** [comment]
I've just seen that ADLX SDK was updated recently to v.1.1, but I don't know if this changes something regarding the issue.

https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/releases/tag/v1.1

**Comment by DevTechProfile** [comment]
I've already updated the latest ADLX version.

**Comment by rphlrmblt** [comment]
Hello, just to add some salt : I've the same issue on two computers : Ryzen 9 5900X + 6700 XT and Ryzen 5 5600X + 6700 XT. Tried the ADL fallback but no improvement.

**Comment by DevTechProfile** [comment]
Got some tips from AMD dev(?!).  I've changed to ADLX API calls. Please check the following version (Build 110): 

https://archive.capframex.com/

**Comment by RodroG-85** [comment]
> Got some tips from an AMD dev(?!). I've changed the ADLX API calls. Please check the following version (Build 110):
> 
> https://archive.capframex.com/

Thank you! I will check it and will report back.

**Comment by rphlrmblt** [comment]
It seems better with the 110 version on the 5900X, I'll check also on the 5600X.

**Comment by RodroG-85** [comment]
@DevTechProfile CX CPU utilization on idle/desktop conditions is slightly better using build 110, but the issue persists. Using 110 ver, the app's CPU usage continuously fluctuates from 0.2 to 0.8% on idle/desktop, and on the same conditions with "ADL Fallback" enabled, the CX CPU usage now spikes from 0% to 0.1% all the time.

AMD should further mitigate CPU usage for their ADLX API calls.

**Comment by DevTechProfile** [comment]
Working on it. This has nothing to do with the AMD library.

**Comment by RodroG-85** [comment]
> Working on it. This has nothing to do with the AMD library.
> 
> Edit... it has something to do with the ADLX... ^^

What a pity @DevTechProfile

So, can you do something to resolve or further mitigate the issue?

**Comment by DevTechProfile** [comment]
Looks like I've already fix it. Will upload a new version asap.

**Comment by DevTechProfile** [comment]
New problem, TBP is not being detected any longer. This AMD stuff kills me...

**Comment by RodroG-85** [comment]
> New problem, TBP is not being detected any longer. This AMD stuff kills me...

@DevTechProfile how is it going?

**Comment by DevTechProfile** [comment]
> @DevTechProfile how is it going?

I tried a lot of variants but at the end I came to the conclusion that the ADLX causes a significant CPU overhead, no matter what API calls I am using. It's up to AMD to fix that.

**Comment by DevTechProfile** [comment]
> > I tried a lot of variants but at the end I came to the conclusion that the ADLX causes a significant CPU overhead, no matter what API calls I am using. It's up to AMD to fix that.
> 
> I hope the AMD guys do something and don't ignore the issue or take years to fix this CPU overhead. Given the current situation, you could add a warning informing the users about the issue.

AMD has fixed the issue as it seems. Try the latest Adrenalin driver together with latest beta on https://archive.capframex.com/.

**Comment by rphlrmblt** [comment]
My **stupid "60+ seconds" idle** on one of my PCs (an 5600X)  :

- With AMD 23.12.1 but NO CapFrameX in background :

<img width="996" alt="2023-12-09 222335" src="https://github.com/CXWorld/CapFrameX/assets/4006281/e3c223c9-bee8-4c35-bc2d-10132ef145db">

- With AMD 23.12.1 AND CapFrameX 1.7.2beta rev 111 : 

<img width="996" alt="2023-12-09 221848" src="https://github.com/CXWorld/CapFrameX/assets/4006281/ffd8fca0-c189-4e0b-a8a2-24d09ff21269">

- With AMD 23.11.1 AND CapFrameX 1.7.2beta rev 111 : 

<img width="996" alt="Capture d'écran 2023-11-14 231812" src="https://github.com/CXWorld/CapFrameX/assets/4006281/17ab6b79-16e7-402c-a863-b35da0331d04">

- In August : 

![2023-08-31 222249](https://github.com/CXWorld/CapFrameX/assets/4006281/a6d017c1-5ff6-44f1-b803-689f1cecec60)


The improvements since the report are noticeable, especially on low end CPU (like 5600X), because on the 5900X with an 6700XT , even the 1.7.2beta rev111 improved things in he same test.

**Comment by RodroG-85** [comment]
> AMD has fixed the issue as it seems. Try the latest Adrenalin driver together with latest beta on https://archive.capframex.com/.

Ok, I'm going to check this combo.

**Comment by DevTechProfile** [comment]
I am glad that the issue is fixed now.

**Comment by RodroG-85** [comment]
Sadly, the issue is back using the latest 1.7.2 release build together with 24.1.1 Adrenalin drivers.
